---
- hosts: webserver

  tasks:
    - ping: ~

    - name: Install Git VCS
      become: true
      apt:
        name: git
        state: latest

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe
